server:
  port: 8090
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,openapi,swagger-ui"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "authentication"
    schema: "public"
    username: "postgres"
    password: "root"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8090"
logging:
  level:
    root: INFO
  file:
    name: logs/crediya.log